project:
  type: website
  output-dir: docs
  execute-dir: project

website:
  title: "Hatespeech Textmining Blog"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/Timo-Sa

format:
  html:
    theme: cosmo
    css: styles.css

lang: de